Clicker1988/administration

admin/application/controllers/Rest_controller.php

test adjustment

---

admin/application/controllers/Employee_controller.php
admin/application/controllers/Payroll_controller.php
admin/application/controllers/Rest_controller.php
admin/application/models/Payroll.php
admin/application/views/employees/employee_dashboard.php

* Dashboard
* OT Request View / API
* Leave Request View

Adjustment for today

---

admin/application/views/employees/employee_dashboard.php

Adjustment

---

admin/application/controllers/Main_controller.php
admin/application/controllers/Payroll_controller.php
admin/application/models/Payroll.php
admin/application/views/main.php
admin/application/views/payroll/deduction_type.php
admin/application/views/payroll/timesheet_type.php

New code for CRUD timesheet type.

Timesheet Type Update

---

admin/application/controllers/Payroll_controller.php
admin/application/controllers/Rest_controller.php
admin/application/models/Payroll.php
admin/application/views/employees/employee_dashboard.php
admin/application/views/main.php
admin/application/views/payroll/deduction_master.php

New Code for Deduction Master Table

Deduction Master Crud

---

admin/application/views/main.php
admin/public/js/custom.js

adjustments for the logo

---

admin/application/controllers/Payroll_controller.php
admin/application/views/payroll/leave_request.php

Leave Request

---

admin/application/controllers/Payroll_controller.php
admin/application/models/Payroll.php
admin/application/views/main.php
admin/application/views/payroll/process_payroll.php

* Show Timesheet Logs onclick
* Hours rendered visible in table

Adjustment for Process Payroll

---

admin/application/controllers/Main_controller.php
admin/application/controllers/Project_controller.php
admin/application/models/Project.php
admin/application/views/main.php
admin/application/views/projects/project_bidding.php

New Project Bidding

---

admin/application/controllers/Project_controller.php
admin/application/views/projects/project_bidding.php

Adjustment Design

---

admin/application/config/routes.php
admin/application/controllers/Admin_controller.php
admin/application/controllers/Crm_controller.php
admin/application/controllers/Employee_controller.php
admin/application/controllers/Main_controller.php
admin/application/controllers/Payroll_controller.php
admin/application/controllers/Project_controller.php
admin/application/models/Users.php
admin/application/views/admin/admin_list.php
admin/application/views/employees/employee_dashboard.php
admin/application/views/employees/employee_department.php
admin/application/views/employees/employee_designation.php
admin/application/views/employees/employee_list.php
admin/application/views/employees/employee_type.php
admin/application/views/main.php
admin/application/views/payroll/deduction_master.php
admin/application/views/payroll/deduction_type.php
admin/application/views/payroll/leave_request.php
admin/application/views/payroll/leave_type.php
admin/application/views/payroll/timesheet_type.php
admin/application/views/projects/materials.php
admin/application/views/projects/project_bidding.php
admin/application/views/projects/project_list.php
admin/application/views/projects/project_types.php
admin/application/views/projects/rate_equipment.php
admin/application/views/projects/rate_labor.php

* CRUD for Auth Accounts
* Level Restrictions

Admin Page

---

admin/application/config/routes.php
admin/application/controllers/Estimation_controller.php
admin/application/controllers/Main_controller.php
admin/application/models/Estimation.php
admin/application/views/estimation/estimation_build.php
admin/application/views/main.php
admin/public/css/estimate.css

Estimation Save Retrieve

---

admin/application/config/config.php

Required to load composer module of Google Cloud

Composer Autoload

---

admin/application/controllers/Admin_controller.php
admin/application/controllers/Main_controller.php
admin/application/views/admin/account_manager.php
admin/application/views/main.php

* Added account manager for use to change fullname and password
* Changed Name to session name
* Changed Link Create Project to Create Estimation
* Removed other images not used

Account Info Changes

---

admin/application/views/login.php
admin/application/views/main.php
admin/public/css/login.css

* Login Design
* CRM features Link

Adjustments 07/26/2018

---

admin/application/controllers/Project_controller.php

* Removed validation from fields
- except (job_name and bid_date)
* Make background-color:red if incomplete details in table

Adjustment for Project Bidding page

---

admin/application/controllers/Infokit_controller.php

Infokit wrong URL

---

admin/application/controllers/Employee_controller.php
admin/application/controllers/Infokit_controller.php
admin/application/controllers/Project_controller.php
admin/application/views/employees/employee_department.php
admin/application/views/employees/employee_designation.php
admin/application/views/employees/employee_type.php
admin/application/views/employees/employee_update_list.php
admin/application/views/infokit/infokit_lesson.php
admin/application/views/projects/materials.php
admin/application/views/projects/project_bidding.php
admin/application/views/projects/project_list.php
admin/application/views/projects/project_types.php
admin/application/views/projects/rate_equipment.php
admin/application/views/projects/rate_labor.php

* Preview before edit.
* Fixed upload for Infokit and Project Bidding

08062018 New Updates

---

admin/application/controllers/Employee_controller.php
admin/application/controllers/Main_controller.php
admin/application/controllers/Project_controller.php
admin/application/models/Project.php
admin/application/views/employees/employee_new_list.php
admin/application/views/employees/employee_update_list.php
admin/application/views/projects/project_bidding.php

* Project Bidding searchable job name added
* Employee Nickname added

Adjustment 08/07/2018

---

.gitignore
admin/application/controllers/Project_controller.php
admin/application/views/projects/project_bidding.php

* Adjustment on Preview in Project Bidding

Adjustment 08092018

---

admin/application/controllers/Admin_controller.php
admin/application/controllers/Payroll_controller.php
admin/application/models/Payroll.php
admin/application/views/admin/admin_list.php
admin/application/views/payroll/deduction_master.php
admin/application/views/payroll/deduction_type.php
admin/application/views/payroll/leave_request.php
admin/application/views/payroll/leave_type.php
admin/application/views/payroll/payroll_period.php
admin/application/views/payroll/timesheet_type.php
admin/application/views/projects/rate_equipment.php

* Payroll Module
* Account Module

Preview Mode
